name: CMake + vcpkg Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install vcpkg
      - name: Cache vcpkg
        id: cache-vcpkg
        uses: actions/cache@v4
        with:
          path: vcpkg
          key: ${{ runner.os }}-vcpkg
          restore-keys: ${{ runner.os }}-vcpkg

      # 2.2 Install X11 development libraries
      - name: Install X11 development libraries
        run: sudo apt-get update && sudo apt-get install -y libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
        if: runner.os != 'Windows'

      # 2.5. Install vcpkg (Linux o Windows)
      - name: Install vcpkg
        if: steps.cache-vcpkg.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          if ($env:RUNNER_OS -eq "Windows") {
            .\vcpkg\bootstrap-vcpkg.bat
          } else {
            ./vcpkg/bootstrap-vcpkg.sh
          }

      # 3. Install dependencies
      - name: Install dependencies via vcpkg
        run: ./vcpkg/vcpkg install --clean-after-build
        shell: bash
        if: runner.os != 'Windows'

      - name: Install dependencies via vcpkg (Windows)
        run: .\vcpkg\vcpkg.exe install --clean-after-build
        shell: powershell
        if: runner.os == 'Windows'

      # 4. Creare build folder
      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release

      # 5. Compile
      - name: Build
        run: cmake --build build --config Release

      # 6. update results
      #- name: Upload artifacts
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: ${{ runner.os }}-build
      #    path: build
